In [1]:
import pandas as pd

raw = pd.read_csv("../raw_data/anand_vihar/Raw_Data_2025_site_301_anand_vihar_delhi_dpcc_1Hr.csv")
raw.head()

,Timestamp,PM2.5 (µg/m³),PM10 (µg/m³),NO (µg/m³),NO2 (µg/m³),NOx (ppb),NH3 (µg/m³),SO2 (µg/m³),CO (mg/m³),Ozone (µg/m³),...,MP-Xylene (µg/m³),AT (°C),RH (%),WS (m/s),WD (deg),RF (mm),TOT-RF (mm),SR (W/mt2),BP (mmHg),VWS (m/s)
0,2025-01-01 00:00:00,251.0,374.0,102.03,58.83,114.27,74.83,13.20,2.81,1.93,...,NaN,11.10,89.00,0.33,251.0,NaN,0.0,5.0,740.0,NaN
1,2025-01-01 01:00:00,269.0,437.0,102.10,61.60,115.80,74.32,12.35,2.74,3.05,...,NaN,10.85,89.75,0.35,251.0,NaN,0.0,5.0,740.0,NaN
2,2025-01-01 02:00:00,238.0,326.0,59.90,63.22,82.35,81.50,14.50,2.38,4.08,...,NaN,11.08,89.25,0.68,251.0,NaN,0.0,5.0,740.0,NaN
3,2025-01-01 03:00:00,227.0,324.0,44.08,61.25,68.40,70.03,16.45,2.00,2.50,...,NaN,11.40,86.50,1.05,251.0,NaN,0.0,5.0,740.0,NaN
4,2025-01-01 04:00:00,286.0,381.0,31.90,51.35,53.25,66.12,15.75,1.81,2.55,...,NaN,11.42,85.50,0.60,251.0,NaN,0.0,5.0,740.0,NaN

In [2]:
import glob

stations = ["anand_vihar","rohini","rk_puram","punjabi_bagh","ito","okhla"]
station_dfs = []
for station in stations:
    files = glob.glob(f"../raw_data/{station}/*.csv")
    dfs = [pd.read_csv(f) for f in files]
    for d in dfs:
        d['Timestamp'] = pd.to_datetime(d['Timestamp'], format='mixed', dayfirst=True)
    sdf = pd.concat(dfs).sort_values('Timestamp').reset_index(drop=True)
    station_dfs.append(sdf)
all_stations = pd.concat(station_dfs).reset_index(drop=True)
all_stations.shape

(512640, 25)

In [3]:
raw.columns

Index(['Timestamp', 'PM2.5 (µg/m³)', 'PM10 (µg/m³)', 'NO (µg/m³)',
       'NO2 (µg/m³)', 'NOx (ppb)', 'NH3 (µg/m³)', 'SO2 (µg/m³)', 'CO (mg/m³)',
       'Ozone (µg/m³)', 'Benzene (µg/m³)', 'Toluene (µg/m³)', 'Xylene (µg/m³)',
       'O Xylene (µg/m³)', 'Eth-Benzene (µg/m³)', 'MP-Xylene (µg/m³)',
       'AT (°C)', 'RH (%)', 'WS (m/s)', 'WD (deg)', 'RF (mm)', 'TOT-RF (mm)',
       'SR (W/mt2)', 'BP (mmHg)', 'VWS (m/s)'],
      dtype='object')

In [4]:
raw.shape

(8760, 25)

In [5]:
raw.isna().sum()

Timestamp                 0
PM2.5 (µg/m³)           616
PM10 (µg/m³)            608
NO (µg/m³)              581
NO2 (µg/m³)             471
NOx (ppb)               488
NH3 (µg/m³)             448
SO2 (µg/m³)            1066
CO (mg/m³)              466
Ozone (µg/m³)           675
Benzene (µg/m³)         622
Toluene (µg/m³)         622
Xylene (µg/m³)         8760
O Xylene (µg/m³)       8760
Eth-Benzene (µg/m³)    8760
MP-Xylene (µg/m³)      8760
AT (°C)                 394
RH (%)                  400
WS (m/s)                410
WD (deg)                458
RF (mm)                8760
TOT-RF (mm)               0
SR (W/mt2)              400
BP (mmHg)               400
VWS (m/s)              8760
dtype: int64

In [6]:
raw = raw.drop(columns=['Xylene (µg/m³)','O Xylene (µg/m³)','Eth-Benzene (µg/m³)'])

In [7]:
raw['Timestamp'] = pd.to_datetime(
    raw['Timestamp'],
    format='mixed',
    dayfirst=True
)

In [8]:
raw = raw.set_index('Timestamp')

In [9]:
aqi_jan = pd.read_excel('../aqi_target/2025/AQI_Data_City_Level_Delhi_January_2025_Hourly.xlsx')

In [10]:
aqi_long = aqi_jan.melt(id_vars='Date', var_name='Hour', value_name='AQI')

In [11]:
aqi_long["Timestamp"] = pd.to_datetime("2025-01-" + aqi_long["Date"].astype(str).str.zfill(2) + " " + aqi_long["Hour"], format="%Y-%m-%d %H:%M")

In [12]:
aqi_long.head()

   Date   Hour    AQI  Timestamp
0     1  00:00  314.0 2025-01-01
1     2  00:00  320.0 2025-01-02
2     3  00:00  331.0 2025-01-03
3     4  00:00  383.0 2025-01-04
4     5  00:00  379.0 2025-01-05

In [13]:
import glob

months = {1:'January',2:'February',3:'March',4:'April',5:'May',6:'June',7:'July',8:'August',9:'September',10:'October',11:'November',12:'December'}
all_months = []
for num, name in months.items():
    file = glob.glob(f"../aqi_target/2025/AQI_Data_City_Level_Delhi_{name}_2025_Hourly.xlsx")
    if not file:
        file = glob.glob(f"../aqi_target/2025/AQI_Data_City_Level_Delhi_{name}_2025_Hourly*.xlsx")
    df = pd.read_excel(file[0])
    long = df.melt(id_vars='Date', var_name='Hour', value_name='AQI')
    long['Timestamp'] = pd.to_datetime(f"2025-{num:02d}-" + long['Date'].astype(str).str.zfill(2) + " " + long['Hour'], format="%Y-%m-%d %H:%M")
    long = long.drop(columns=['Date','Hour'])
    all_months.append(long)
aqi_full_year = pd.concat(all_months).sort_values('Timestamp').reset_index(drop=True)

In [14]:
aqi_full_year.shape

(8760, 2)

In [15]:
merged = pd.merge(raw, aqi_full_year.set_index("Timestamp"), left_index=True, right_index=True, how="inner")
merged.shape

(8760, 22)

In [16]:
merged.head(
)

,PM2.5 (µg/m³),PM10 (µg/m³),NO (µg/m³),NO2 (µg/m³),NOx (ppb),NH3 (µg/m³),SO2 (µg/m³),CO (mg/m³),Ozone (µg/m³),Benzene (µg/m³),...,AT (°C),RH (%),WS (m/s),WD (deg),RF (mm),TOT-RF (mm),SR (W/mt2),BP (mmHg),VWS (m/s),AQI
Timestamp,,,,,,,,,,,,,,,,,,,,,
2025-01-01 00:00:00,251.0,374.0,102.03,58.83,114.27,74.83,13.20,2.81,1.93,6.23,...,11.10,89.00,0.33,251.0,NaN,0.0,5.0,740.0,NaN,314.0
2025-01-01 01:00:00,269.0,437.0,102.10,61.60,115.80,74.32,12.35,2.74,3.05,6.25,...,10.85,89.75,0.35,251.0,NaN,0.0,5.0,740.0,NaN,320.0
2025-01-01 02:00:00,238.0,326.0,59.90,63.22,82.35,81.50,14.50,2.38,4.08,5.72,...,11.08,89.25,0.68,251.0,NaN,0.0,5.0,740.0,NaN,324.0
2025-01-01 03:00:00,227.0,324.0,44.08,61.25,68.40,70.03,16.45,2.00,2.50,6.00,...,11.40,86.50,1.05,251.0,NaN,0.0,5.0,740.0,NaN,328.0
2025-01-01 04:00:00,286.0,381.0,31.90,51.35,53.25,66.12,15.75,1.81,2.55,5.72,...,11.42,85.50,0.60,251.0,NaN,0.0,5.0,740.0,NaN,328.0

In [17]:
merged.to_csv("../processed_data/anand_vihar_2025_merged.csv")

In [18]:
import glob

years = range(2018, 2026)
all_data = []
for year in years:
    for num, name in months.items():
        file = glob.glob(f"../aqi_target/{year}/AQI_Data_City_Level_Delhi_{name}_{year}_Hourly.xlsx")
        if not file:
            file = glob.glob(f"../aqi_target/{year}/AQI_Data_City_Level_Delhi_{name}_{year}_Hourly*.xlsx")
        df = pd.read_excel(file[0])
        long = df.melt(id_vars='Date', var_name='Hour', value_name='AQI')
        hour_clean = long['Hour'].astype(str).str[:5]
        long['Timestamp'] = pd.to_datetime(f"{year}-{num:02d}-" + long['Date'].astype(str).str.zfill(2) + " " + hour_clean, format="%Y-%m-%d %H:%M")
        long = long.drop(columns=['Date','Hour'])
        all_data.append(long)
aqi_all_years = pd.concat(all_data).sort_values('Timestamp').reset_index(drop=True)
aqi_all_years.shape

(70128, 2)

In [19]:
files = glob.glob("../raw_data/anand_vihar/*.csv")
raw_list = []
for file in files:
    df = pd.read_csv(file)
    df['Timestamp'] = pd.to_datetime(df['Timestamp'], format='mixed', dayfirst=True)
    raw_list.append(df)
raw_all_years = pd.concat(raw_list).sort_values('Timestamp').reset_index(drop=True)
raw_all_years = raw_all_years[raw_all_years['Timestamp'].dt.year.between(2018, 2025)]
raw_all_years.shape

(70128, 25)

In [20]:
raw_all_years = raw_all_years.set_index('Timestamp')
aqi_all_years_idx = aqi_all_years.set_index('Timestamp')
merged_all = pd.merge(raw_all_years, aqi_all_years_idx, left_index=True, right_index=True, how='inner')
merged_all.shape

(70128, 25)

In [21]:
import glob

stations = ["anand_vihar","rohini","rk_puram","punjabi_bagh","ito","okhla"]
station_dfs = []
for station in stations:
    files = glob.glob(f"../raw_data/{station}/*.csv")
    dfs = [pd.read_csv(f) for f in files]
    for d in dfs:
        d['Timestamp'] = pd.to_datetime(d['Timestamp'], format='mixed', dayfirst=True)
    sdf = pd.concat(dfs).sort_values('Timestamp').reset_index(drop=True)
    sdf = sdf[sdf['Timestamp'].dt.year.between(2018, 2025)]
    station_dfs.append(sdf)
all_stations = pd.concat(station_dfs).reset_index(drop=True)
all_stations.shape

(420768, 25)

In [22]:
numeric_cols = all_stations.select_dtypes(include='number').columns
city_avg = all_stations.groupby('Timestamp')[numeric_cols].mean().reset_index()
city_avg.shape

(70128, 25)

In [23]:
final = pd.merge(city_avg.set_index('Timestamp'), aqi_all_years_idx, left_index=True, right_index=True, how='inner')
final.shape
final.head()

,PM2.5 (µg/m³),PM10 (µg/m³),NO (µg/m³),NO2 (µg/m³),NOx (ppb),NH3 (µg/m³),SO2 (µg/m³),CO (mg/m³),Ozone (µg/m³),Benzene (µg/m³),...,AT (°C),RH (%),WS (m/s),WD (deg),RF (mm),TOT-RF (mm),SR (W/mt2),BP (mmHg),VWS (m/s),AQI
Timestamp,,,,,,,,,,,,,,,,,,,,,
2018-01-01 00:00:00,557.5000,684.000000,285.650000,106.236667,NaN,101.530000,18.620000,7.036667,32.846667,11.790000,...,8.183333,80.556667,0.300000,149.223333,NaN,0.0,8.110000,731.00,-0.045,413.0
2018-01-01 01:00:00,556.5000,659.833333,389.325000,88.193333,NaN,102.106667,8.446667,7.366667,32.133333,10.906667,...,7.886667,81.193333,0.300000,127.223333,NaN,0.0,8.193333,730.96,-0.040,414.0
2018-01-01 02:00:00,553.4375,622.666667,334.100000,74.326667,NaN,104.786667,13.540000,6.240000,30.170000,10.646667,...,7.476667,82.113333,0.303333,110.110000,NaN,0.0,8.166667,730.96,-0.040,415.0
2018-01-01 03:00:00,530.9175,590.333333,208.696667,64.690000,369.60,95.913333,8.285000,3.636667,25.350000,10.436667,...,6.863333,82.806667,0.350000,113.250000,NaN,0.0,8.333333,730.71,-0.045,415.0
2018-01-01 04:00:00,420.2500,568.250000,161.626667,76.763333,300.97,89.293333,5.836667,2.293333,20.103333,9.256667,...,6.946667,83.720000,0.410000,139.026667,NaN,0.0,8.833333,731.21,-0.010,415.0

In [24]:
final.to_csv("../processed_data/delhi_6station_avg_2018_2025.csv")